### ISSUE TITLE
[Refactor] category DDD로 리펙토링

### ISSUE THREAD

**Issue by heechul90** [woorinpang/store-service#107]
# Description
- category 패키지 ddd 스타리로 리펙토링하기

# Todos
- [x] hairshop category package
- [x] hairshop category test package
- [x] cafe category package
- [x] cafe category test package
- [x] restaurant category package
- [x] restaurant category test package
